# Site settings
title: Shrey Desai
email: shreydesai@me.com
description: >
  Weekly reveries on undergraduate life, computer science, and software engineering
baseurl: ""
url: "https://shreydesai.github.com"
twitter_username: shreydesai
github_username:  shreydesai

# Build settings
markdown: kramdown
sass:
  sass_dir: css/bower_components/bootstrap-sass/assets/stylesheets
  style: compressed
